#!/bin/bash

# Copyright (C) 2019  Stefan Vargyas
# 
# This file is part of Html-Cref.
# 
# Html-Cref is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# Html-Cref is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with Html-Cref.  If not, see <http://www.gnu.org/licenses/>.

#
# File generated by a command like:
# $ html-cref-gentest -w14 -R
#

test "$1" == "-q" &&
q="q" ||
q=""

is-builtin()
{
    ../src/html-cref --help|
    { ! grep -Fqe "-p|--cref-parser="; }
}

is-builtin &&
t="builtin" ||
t="modules"

r=($(./test-$t.sh -w14 -c ${q:+-q}))

[ -z "$q" -o "${r[1]}" -gt 0 ] &&
echo >&2

echo "test cases passed: ${r[0]}"
echo "test cases failed: ${r[1]}"

exit $(( ${r[1]} != 0 ))

