#!/bin/bash

# Copyright (C) 2019  Stefan Vargyas
# 
# This file is part of Html-Cref.
# 
# Html-Cref is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# Html-Cref is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with Html-Cref.  If not, see <http://www.gnu.org/licenses/>.

#
# File generated by a command like:
# $ html-cref-gentest -C modules:bre2c
#

[[ "$1" =~ ^-u[0-9]+$ ]] &&
u="${1:2}" ||
u=""

diff -u$u -L bre2c.old <(echo \
'$ shopt -s extglob
$ . test-funcs.sh
$ validate-names bre2c
$ validate-names -r bre2c
$ validate-strict-prefixes bre2c
$ validate-strict-prefixes -r bre2c
$ test-crefs bre2c'
) -L bre2c.new <(
echo '$ shopt -s extglob'
shopt -s extglob 2>&1 ||
echo 'command failed: shopt -s extglob'

echo '$ . test-funcs.sh'
. test-funcs.sh 2>&1 ||
echo 'command failed: . test-funcs.sh'

echo '$ validate-names bre2c'
validate-names bre2c 2>&1 ||
echo 'command failed: validate-names bre2c'

echo '$ validate-names -r bre2c'
validate-names -r bre2c 2>&1 ||
echo 'command failed: validate-names -r bre2c'

echo '$ validate-strict-prefixes bre2c'
validate-strict-prefixes bre2c 2>&1 ||
echo 'command failed: validate-strict-prefixes bre2c'

echo '$ validate-strict-prefixes -r bre2c'
validate-strict-prefixes -r bre2c 2>&1 ||
echo 'command failed: validate-strict-prefixes -r bre2c'

echo '$ test-crefs bre2c'
test-crefs bre2c 2>&1 ||
echo 'command failed: test-crefs bre2c'
)

