#!/bin/bash

# Copyright (C) 2019  Stefan Vargyas
# 
# This file is part of Html-Cref.
# 
# Html-Cref is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# Html-Cref is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with Html-Cref.  If not, see <http://www.gnu.org/licenses/>.

#
# File generated by a command like:
# $ html-cref-gentest -C modules:wtrie
#

[[ "$1" =~ ^-u[0-9]+$ ]] &&
u="${1:2}" ||
u=""

diff -u$u -L wtrie.old <(echo \
'$ shopt -s extglob
$ . test-funcs.sh
$ validate-names wtrie
$ validate-names -r wtrie
$ validate-strict-prefixes wtrie
$ validate-strict-prefixes -r wtrie
$ test-crefs wtrie'
) -L wtrie.new <(
echo '$ shopt -s extglob'
shopt -s extglob 2>&1 ||
echo 'command failed: shopt -s extglob'

echo '$ . test-funcs.sh'
. test-funcs.sh 2>&1 ||
echo 'command failed: . test-funcs.sh'

echo '$ validate-names wtrie'
validate-names wtrie 2>&1 ||
echo 'command failed: validate-names wtrie'

echo '$ validate-names -r wtrie'
validate-names -r wtrie 2>&1 ||
echo 'command failed: validate-names -r wtrie'

echo '$ validate-strict-prefixes wtrie'
validate-strict-prefixes wtrie 2>&1 ||
echo 'command failed: validate-strict-prefixes wtrie'

echo '$ validate-strict-prefixes -r wtrie'
validate-strict-prefixes -r wtrie 2>&1 ||
echo 'command failed: validate-strict-prefixes -r wtrie'

echo '$ test-crefs wtrie'
test-crefs wtrie 2>&1 ||
echo 'command failed: test-crefs wtrie'
)

