// Copyright (C) 2019  Stefan Vargyas
// 
// This file is part of Html-Cref.
// 
// Html-Cref is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Html-Cref is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Html-Cref.  If not, see <http://www.gnu.org/licenses/>.

//
// This file was generated by a command like:
// $ html-cref-gen --gen-cref-overrides --heading
//

    [0x00] = 0x20ac,
    [0x02] = 0x201a,
    [0x03] = 0x0192,
    [0x04] = 0x201e,
    [0x05] = 0x2026,
    [0x06] = 0x2020,
    [0x07] = 0x2021,
    [0x08] = 0x02c6,
    [0x09] = 0x2030,
    [0x0a] = 0x0160,
    [0x0b] = 0x2039,
    [0x0c] = 0x0152,
    [0x0e] = 0x017d,
    [0x11] = 0x2018,
    [0x12] = 0x2019,
    [0x13] = 0x201c,
    [0x14] = 0x201d,
    [0x15] = 0x2022,
    [0x16] = 0x2013,
    [0x17] = 0x2014,
    [0x18] = 0x02dc,
    [0x19] = 0x2122,
    [0x1a] = 0x0161,
    [0x1b] = 0x203a,
    [0x1c] = 0x0153,
    [0x1e] = 0x017e,
    [0x1f] = 0x0178,

